#!/bin/bash

# automating the creation of new users on Linux server

# setting name of csv_file and group name
CSV_FILE=names.csv

GROUP_NAME=developers

# setting name of ssh directory for skel
SSH_SKEL=/etc/skel/.ssh

# variable for puclic key file
AUTH=authorized_keys

# password variable
PASSWORD=password


# check if group exist
if [ $(getent group developers) ];
then
    echo group already exists
else
    sudo groupadd $GROUP_NAME
    echo group succesfully created
fi

# add ssh folder to skel directory
# using command test -d 
if [ -d "$SSH_SKEL" ];
then
    echo $SSH_SKEL already exists
else
    sudo mkdir -p $SSH_SKEL
    sudo touch $SSH_SKEL/$AUTH
    sudo bash -c "cat $AUTH >> $SSH_SKEL/authorized_keys"
fi

# create each user on the server
while IFS= read USERNAME
    do
        # check if the username already exists
        if [ $(getent passwd $USERNAME) ];
        then 
            echo $USERNAME already exists
        else
            sudo useradd -m -G $GROUP_NAME -s /bin/bash $USERNAME
            sudo echo -e "$PASSWORD\n$PASSWORD" | sudo passwd "${USERNAME}"
            sudo passwd -x 10 "${USERNAME}"
            sudo chmod 700 /home/$USERNAME/.ssh
            sudo chmod 644 /home/$USERNAME/.ssh/$AUTH
            echo "$USERNAME successfully created"
        fi
    done < $CSV_FILE
exit 0